version: "3"
services:
    web:
        restart: always
        image: nginx:latest
        ports:
            - "8001:80"
        volumes:
            - "./typecho:/data/wwwroot/typecho"
            - "./config/nginx/typecho.conf:/etc/nginx/conf.d/default.conf"
            - "./logs:/data/wwwlogs"
    php:
        build:
            context: app/php
        volumes:
            - "./typecho:/data/wwwroot/typecho"