version: "3"
services:
    http:
        restart: always
        image: nginx:latest
        ports:
            - "8001:80"
        volumes:
            - "/opt/typecho/instance:/data/wwwroot/typecho"
            - "/opt/typecho/config/nginx/typecho.conf:/etc/nginx/conf.d/default.conf"
            - "/opt/typecho/logs:/data/wwwlogs"
    php:
        build:
            context: app/php
        volumes:
            - "/opt/typecho/typecho:/data/wwwroot/typecho"
